name: Build ICEland binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Install musl tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build aarch64 static binary
        run: |
          cargo build --release --target aarch64-unknown-linux-musl

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: iceland-aarch64-linux
          path: target/aarch64-unknown-linux-musl/release/iceland